### ISSUE TITLE
Embedded Sentinel-2 manifest schema is not self-contained

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/safecheck#5]
@ghajduch @avalentino

Running safecheck on `S2A_MSIL1C_20230601T071621_N0509_R006_T40VFQ_20230601T110126.SAFE` now gives:

```
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}redefine': Failed to load the document '../../../../../org/ccsds/xfdu/xfdu.xsd' for redefinition., line 44
```

Do you have a self-contained schema?

**Comment by avalentino** [comment]
Sorry, not a self-contained one.
Next week I can try to ask to a colleague.

**Comment by svniemeijer** [comment]
Note that the S1 manifest schema is just checking the xfdu namespace, it doesn't check any of the product-type specific metadata blocks. We could probably also use a revised one of that for S2 (which means we could still go for one embedded schema again).

**Comment by svniemeijer** [comment]
Alternatively, we could add additional schema files for the other namespaces used in the manifest file (e.g. 'safe', 's1sar', ...), but these would then need to be self-contained (the official term for combining multiple schema files into one is called 'flattening').
Adding a schema for the 'gml' namespace might be tricky, since it is rather big, but it might be possible to add a schema just for the subset of elements that are used by S1/S2.

I think this would be the ideal way forward.

**Comment by avalentino** [comment]
I agree.
Since we now have the a dedicated folder to store XSD files I think that we can safely add the necessary files to have more accurate checks.
Regarding schema flattening, I have no experience with it. Do you have tools to prepare the flattened schemas?

**Comment by svniemeijer** [comment]
Unfortunately not.

But the short term problem is only for the xfdu namespace schema file. It should not be too hard to create a variant of the one we have for S1 for S2 such that safecheck works correctly again for S2.

Adding schemas for additional namespaces should be captured by a separate ticket if we want this.

**Comment by svniemeijer** [comment]
Support for Sentinel-2 has been removed. Feel free to provide a new PR if you have something that actually works.
